---
namespace: ivansible
name: termux
version: 1.0.0

description: Ansible collection for Termux roles

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - android
  - termux
  - proot
  - ubuntu

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/termux
documentation: https://github.com/ivansible/termux
homepage: https://github.com/ivansible/termux
issues: https://github.com/ivansible/termux/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
