---
## see:
## https://wiki.termux.com/wiki/Termux-services

- name: install termux service framwork
  command: "pkg install {{ termux_pkg_opts }} termux-services"
  environment: "{{ termux_pkg_env }}"
  register: _services_install
  until: _services_install is successful
  changed_when: _services_install.stdout |d('') is search(termux_pkg_changed)

- name: setup ssh service directory
  shell:
    cmd: |
      pkg uninstall {{ termux_pkg_opts }} openssh
      pkg install   {{ termux_pkg_opts }} openssh
    creates: "{{ termux_svc_dir }}/sshd"
  environment: "{{ termux_pkg_env }}"

- name: activate termux service daemon
  command:
    cmd: service-daemon start
    creates: "{{ termux_root_dir }}/usr/var/run/service-daemon.pid"
  environment:
    SVDIR: "{{ termux_svc_dir }}"
    LOGDIR: "{{ termux_log_dir }}"
  register: _services_activate
  until: _services_activate is successful
  delay: 2

- name: wait a little for service daemon to warm up
  wait_for:
    timeout: 5
  when: _services_activate is changed

- name: enable termux ssh service (unless disabled)
  command:
    cmd: sv-enable sshd
    removes: "{{ termux_svc_dir }}/sshd/down"
  environment:
    SVDIR: "{{ termux_svc_dir }}"
    LOGDIR: "{{ termux_log_dir }}"
  when: termux_ssh_autostart |bool

- name: disable termux ssh service (unless enabled)
  command:
    cmd: sv-disable sshd
    creates: "{{ termux_svc_dir }}/sshd/down"
  environment:
    SVDIR: "{{ termux_svc_dir }}"
    LOGDIR: "{{ termux_log_dir }}"
  when: not termux_ssh_autostart |bool

- name: restart termux service daemon (as needed)
  block:
    - name: restart termux service daemon if config changed (will report if it fails)
      # noqa no-changed-when
      command: timeout 10 service-daemon restart
      environment:
        SVDIR: "{{ termux_svc_dir }}"
        LOGDIR: "{{ termux_log_dir }}"
      register: _services_restart
      until: _services_restart is successful
  rescue:
    - name: report failed service daemon restart
      debug:
        msg: service daemon failed to restart (ignored)
  when:
    - _services_install is changed
    - _services_activate is not changed

- name: make termux autostart script
  template:
    src: services/autostart.sh
    dest: "{{ ansible_user_dir }}/autostart"
    mode: 0755
  vars:
    wakelock_comment: "{{ termux_wakelock_autostart |bool |ternary('','#') }}"
    shmem_comment: "{{ termux_shmem |bool |ternary('','#') }}"
    termux_ssh_comment: "{{ termux_ssh_autostart |bool |ternary('','#') }}"
    ubuntu_ssh_comment: "{{ termux_ubuntu_ssh_autostart |bool |ternary('','#') }}"
    ubuntu_start: "{{ termux_ubuntu_start_script }}"
    root_dir: "{{ termux_root_dir }}"
    boot_log: "{{ termux_log_dir }}/boot.log"
  tags:
    - termux_shmem_all

- name: create directory for termux autostart script
  file:
    state: directory
    path: "{{ ansible_user_dir }}/.termux/boot"
    mode: 0755

- name: create link for termux autostart script
  file:
    state: link
    src: ../../autostart
    path: "{{ ansible_user_dir }}/.termux/boot/autostart"

- name: check whether termux-boot is installed
  stat:
    path: /data/data/com.termux.boot
  register: _termux_boot

- name: remind user to install termux-boot
  debug:
    msg:
      - "+------------------------------+"
      - "|  Please install Termux:Boot  |"
      - "+------------------------------+"
  when: not _termux_boot.stat.exists
...
