---
- name: perform root setup of ubuntu in termux
  ansible.builtin.import_tasks: root.yml
  become: true
  when: not termux_mini |bool
  tags:
    - termux_ubuntu_all
    - termuntu_all

- name: setup gui
  ansible.builtin.import_tasks: gui.yml
  become: true
  when:
    - termuntu_install_gui |bool
    - not termux_mini |bool
  tags:
    - termux_ubuntu_gui
    - termuntu_all

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
  tags:
    - termux_ubuntu_all
    - termuntu_all
...
