---
termuntu_system_locale: ~
termuntu_timezone: ~
termuntu_hostname: "{{ inventory_hostname }}"
termuntu_name_android_groups: true

termuntu_core_packages:
  - tzdata
  - locales
  - openssh-server
  - openssh-client
  - file
  - acl
  - gzip
  - unzip
  - iproute2
  - iputils-ping
  - traceroute
  - dnsutils
  - bind9-host
  - curl
  - wget
  - netcat
  - aptitude
  - apt-utils
  - apt-file
  - apt-transport-https
  - software-properties-common
  - python3
  - python3-apt
  - python3-pip
  - "{{ 'python-virtualenv' if ansible_lsb.codename == 'trusty' else 'virtualenv' }}"
  - build-essential
  - bash-completion
  - rsync
  - git
  - vim
  - tmux
  - ncdu
...
